FORMAT: 1A
HOST: https://airiusfans-qa.blynk.cc/


# Login API

## Login [POST] [/api/login]

+ Request (application/x-www-form-urlencoded)

       "email" : "admin@blynk.cc"
       "password" : "84inR6aLx6tZGaQyLrZSEVYCxWW8L88MG+gOn2cncgM=" //SHA256 hash of password salted with username.toLowerCase
        
+ Response 200 (application/json)

        User json with cookie "session".

+ Response 400 (application/json)

        Email or password is empty, user not exists or password is wrong.
        
+ Response 500 (application/json)

        Unexpected server error, probably wrong content-type.

## Invite [POST] [/api/invite]

+ Request (application/x-www-form-urlencoded)

       "token" : "da59f715fe674730bed3dc6aacad399e"
       "password" : "84inR6aLx6tZGaQyLrZSEVYCxWW8L88MG+gOn2cncgM=" //SHA256 hash of password salted with username.toLowerCase

+ Response 200 (application/json)

        User json with cookie "session".

+ Response 400 (application/json)

        Token does not exist.

+ Response 500 (application/json)

        Unexpected server error, probably wrong content-type.

## Send reset password email when not logged [POST] [/sendResetPass]

+ Request (application/x-www-form-urlencoded)

        "email" : "user@blynk.cc"

+ Response 200 (application/json)

        Email was sent.

+ Response 400 (application/json)

        User email field is wrong.

+ Response 400 (application/json)

        Error sending email.

## Reset Password [POST] [/api/resetPass]

+ Request (application/x-www-form-urlencoded)

       "token" : "da59f715fe674730bed3dc6aacad399e"
       "password" : "84inR6aLx6tZGaQyLrZSEVYCxWW8L88MG+gOn2cncgM=" //SHA256 hash of password salted with username.toLowerCase

+ Response 200 (application/json)

        User json with cookie "session".

+ Response 400 (application/json)

        Token does not exist.

+ Response 500 (application/json)

        Unexpected server error, probably wrong content-type.

## Logout [POST] [/api/logout]

+ Request (application/json)
        
+ Response 301 (application/json)

        /dashboard


# Organizations API

## Get list of organizations user has access to [GET] [/api/organization]

+ Request (application/json)

+ Response 200 (application/json)

        List of organizations

+ Response 500 (application/json)

        Unexpected error.


## Get organization assigned to user [GET] [/api/organization/{orgId}]

+ Request (application/json)

+ Response 200 (application/json)

        Json of user organization

+ Response 400 (application/json)

        Cannot find organization with passed id.

+ Response 403 (application/json)

        You are not allowed to access this organization.

+ Response 500 (application/json)

        Unexpected error.


## Get existing locations of organization [GET] [/api/organization/{orgId}/locations]

+ Request (application/json)

+ Response 200 (application/json)

        [
            "Kyiv",
            "Kyiv 2"
        ]

+ Response 403 (application/json)

        You are not allowed to access this organization.


## Create New Organization [PUT] [/api/organization]

+ Request (application/json)

        Full organization json (without id field)

+ Response 200 (application/json)

        Full organization json

+ Response 403 (application/json)

        User is not authorized to make this request.

+ Response 500 (application/json)

        Unexpected error.

## Check if user can be invited [POST] [/api/organization/{orgId}/canInviteUser]

+ Request (application/json)

        {
            "email" : "xxx@gmail.com"
        }

+ Response 200 (application/json)

        "User can be invited"

+ Response 400 (application/json)

        "User already exists in system."


## Update Organization [POST] [/api/organization/{orgId}]

+ Request (application/json)

        Full organization json (with id field)

+ Response 200 (application/json)

        Full organization json

+ Response 403 (application/json)

        User is not authorized to make this request.

+ Response 403 (application/json)

        You are not allowed update to access this organization.

+ Response 500 (application/json)

        Unexpected error.

## Delete Organization [DELETE] [/api/organization/{orgId}]

+ Request (application/json)

+ Response 200 (application/json)

+ Response 403 (application/json)

        User is not authorized to make this request or user tries to remove initial organization.

+ Response 500 (application/json)

        Unexpected error.

## Invite user [POST] [/api/organization/{orgId}/invite]

+ Request (application/json)

        {"email":"USER_I_WANT_INVITE@gmail.com", "name":"Vasya Pupkin", "role":"ADMIN"}

+ Response 200 (application/json)

+ Response 400 (application/json)

        Invalid email.

+ Response 400 (application/json)

        Wrong organization id.

+ Response 403 (application/json)

        User not allowed to send invite or tries to send invite to organization he has no access.

+ Response 500 (application/json)

        Error generating invitation email.


# Organization Users API

## Get organization users [GET] [/api/organization/{orgId}/users]

+ Request (application/json)

+ Response 200 (application/json)

        Json of users belongs to organization

+ Response 400 (application/json)

        Cannot find organization with passed id.

+ Response 403 (application/json)

        You are not allowed to access this organization.

+ Response 500 (application/json)

        Unexpected error.

## Update organization user [POST] [/api/organization/{orgId}/users/update]

+ Request (application/json)

        {"email":"USER_I_WANT_UPDATE@gmail.com", "name":"Vasya Pupkin", "role":"ADMIN"}

+ Response 200 (application/json)

+ Response 400 (application/json)

        Bad data for user update.

+ Response 400 (application/json)

        Cannot find organization with passed id.

+ Response 400 (application/json)

        User not exists.

+ Response 403 (application/json)

        You are not allowed to access this organization.

+ Response 500 (application/json)

        Unexpected error.

## Delete organization users [POST] [/api/organization/{orgId}/users/delete]

+ Request (application/json)

        ["user1@blynk.cc","user2.blynk.cc"]

+ Response 200 (application/json)

+ Response 400 (application/json)

        Cannot find organization with passed id.

+ Response 403 (application/json)

        You are not allowed to access this organization.

+ Response 500 (application/json)

        Unexpected error.


# Account API

## Get Account Info [GET] [/api/account]

+ Request (application/json)

+ Response 200 (application/json)

        User json


## Update Account Info [POST] [/api/account]

+ Request (application/json)

        Full user json

+ Response 200 (application/json)

        Full user json


# Products API

## Get List Of Products [GET] [/api/product]

+ Request (application/json)

+ Response 200 (application/json)

        List of products for current user organization

        [
            {
              "id" : 1,
              "parentId" : 0,
              "name" : "My Product",
              "boardType" : "Arduino UNO",
              "connectionType" : "WI_FI",
              "description" : "Description",
              "logoUrl" : "/static/logo.png",
              "lastModifiedTs" : 1493801505645,
              "createdAt" : 1493801505645,
              "metaFields" : [ {
                "type" : "Number",
                "id" : 1,
                "name" : "Jopa",
                "role" : "STAFF",
                "isMandatory" : false,
                "value" : 123.0
              }, {
                "type" : "Text",
                "id" : 2,
                "name" : "Device Name",
                "role" : "ADMIN",
                "isMandatory" : true,
                "value" : "My Default device Name"
              } ],
              "webDashboard" : {
                "widgets" : [ {
                  "type" : "WEB_LABEL",
                  "id" : 0,
                  "x" : 1,
                  "y" : 2,
                  "color" : 0,
                  "width" : 20,
                  "height" : 10,
                  "tabId" : 0,
                  "label" : "123",
                  "isEnabled" : true,
                  "isDefaultColor" : false,
                  "sources" : [ {
                    "label" : "some Label",
                    "color" : "#334455",
                    "connectMissingPointsEnabled" : false,
                    "sourceType" : "RAW_DATA",
                    "dataStream" : {
                      "id" : 0,
                      "pin" : 1,
                      "pwmMode" : false,
                      "rangeMappingOn" : false,
                      "pinType" : "VIRTUAL",
                      "min" : 0,
                      "max" : 255
                    },
                    "limit" : 10
                  } ]
                }, {
                  "type" : "WEB_LINE_GRAPH",
                  "id" : 0,
                  "x" : 3,
                  "y" : 4,
                  "color" : 0,
                  "width" : 20,
                  "height" : 10,
                  "tabId" : 0,
                  "label" : "graph",
                  "isEnabled" : true,
                  "isDefaultColor" : false,
                  "sources" : [ {
                    "label" : "Some Label",
                    "color" : "#334455",
                    "connectMissingPointsEnabled" : false,
                    "sourceType" : "RAW_DATA",
                    "dataStream" : {
                      "id" : 0,
                      "pin" : 1,
                      "pwmMode" : false,
                      "rangeMappingOn" : false,
                      "pinType" : "VIRTUAL",
                      "min" : 0,
                      "max" : 255
                    },
                    "selectedColumns" : [ {
                      "name" : "load_weight",
                      "label" : "Load Weight",
                      "type" : "COLUMN"
                    } ],
                    "groupByFields" : [ {
                      "name" : "Shift 1",
                      "type" : "METADATA"
                    }, {
                      "name" : "Shift 2",
                      "type" : "METADATA"
                    }, {
                      "name" : "Shift 3",
                      "type" : "METADATA"
                    } ],
                    "sortByFields" : [ {
                      "name" : "load_weight",
                      "label" : "Load Weight",
                      "type" : "COLUMN"
                    } ],
                    "sortOrder" : "ASC",
                    "limit" : 10
                  } ],
                  "isShowTitleEnabled" : false,
                  "isShowLegendEnabled" : false
                } ]
              },
              "deviceCount" : 0,
              "version" : 0
            }
        ]

+ Response 400 (application/json)

        No organization with products.


## Get Product by Id [GET] [/api/product/{productId}]

+ Request (application/json)

        Full product json

+ Response 400 (application/json)

        Product with passed id is not found.

## Create New Product [PUT] [/api/product]

+ Request (application/json)

        {
            "orgId" : 1,
            "product" : {...}
        }

+ Response 200 (application/json)

        Full product json

+ Response 400 (application/json)

        Wrong data for product.

## Update Product [POST] [/api/product]

+ Request (application/json)

        {
            "orgId" : 1,
            "product" : {...}
        }

+ Response 200 (application/json)

        Full product json

+ Response 400 (application/json)

        Wrong data for product.

## Update Product and related devices metadata [POST] [/api/product/updateDevices]

+ Request (application/json)

        {
            "orgId" : 1,
            "product" : {...}
        }

+ Response 200 (application/json)

        Full product json

+ Response 400 (application/json)

        Wrong data for product.

## Can Delete Product [GET] [/api/product/canDeleteProduct/{productId}]

+ Response 200 (application/json)

+ Response 403 (application/json)

## Delete Product [DELETE] [/api/product/{productId}]

+ Request (application/json)

+ Response 200 (application/json)

+ Response 400 (application/json)

        User not allowed to delete product (not admin) or product with passed id not found.

+ Response 500 (application/json)

        Unexpected error.


## Upload API [POST] [/api/upload]

+ Request (multipart/form-data)

        File content.

+ Response 200 (application/json)

        Full path to uploaded image. For example : '/static/FUp_5716167699683281586_logo.png'.
        Product and Org has logoUrl field you need to set with that url

+ Response 400 (application/json)

        Something went wrong during upload.


# Devices API

## Get All devices for user [GET] [/api/devices/{orgId}?orderField={fieldName}&order={orderType}]

+ Request (application/json)

        {fieldName} - field to order by, for example 'name';
        {orderType} - order direction ASC|DESC;

+ Response 200 (application/json)

    [
        {
          "id" : 1,
          "productId" : -1,
          "productName" : "My Product",
          "name" : "My New Device",
          "token" : "18aaf2a2a2ae4c9e9ba0cf9c0e1ef339",
          "status" : "OFFLINE",
          "disconnectTime" : 0,
          "updatedAt" : 0,
          "activatedAt" : 0,
          "activatedBy" : "pupkin@gmail.com",
          "criticalSinceLastView" : 1,
          "warningSinceLastView" : 2,
          "metadataUpdatedAt" : 0,
          "metadataUpdatedBy" : "pupkin@gmail.com",
          "metaFields" : [ {
            "type" : "Number",
            "name" : "Jopa",
            "role" : "STAFF",
            "value" : 123.0
          } ]
        }, {
          "id" : 2,
          "productId" : -1,
          "productName" : "My Product",
          "name" : "My New Device",
          "token" : "d3a1b712802a490f9e95edce53f0091c",
          "status" : "OFFLINE",
          "disconnectTime" : 0,
          "updatedAt" : 0,
          "activatedAt" : 0,
          "activatedBy" : "pupkin@gmail.com",
          "metadataUpdatedAt" : 0,
          "metadataUpdatedBy" : "pupkin@gmail.com",
          "metaFields" : [ {
            "type" : "Number",
            "name" : "Jopa",
            "role" : "STAFF",
            "value" : 123.0
          } ]
        }, {
          "id" : 0,
          "productId" : -1,
          "boardType" : "ESP8266",
          "token" : "7b0a3a61322e41a5b50589cf52d775d1",
          "status" : "OFFLINE",
          "disconnectTime" : 0,
          "updatedAt" : 0
        }
    ]

## Get device by id [GET] [/api/devices/{orgId}/{deviceId}]

+ Request (application/json)

+ Response 200 (application/json)

        {
          "id" : 1,
          "productId" : -1,
          "orgName" : "Blynk Inc.",
          "productName" : "My product",
          "productLogoUrl" : "/productlogourl",
          "name" : "My New Device",
          "token" : "18aaf2a2a2ae4c9e9ba0cf9c0e1ef339",
          "status" : "OFFLINE",
          "disconnectTime" : 0,
          "updatedAt" : 0,
          "metaFields" : [ {
            "type" : "Number",
            "name" : "Jopa",
            "role" : "STAFF",
            "value" : 123.0
          } ]
        }

+ Response 400 (application/json)

    Device not found.

+ Response 403 (application/json)

    You have no access to this device.

## Create New Device [PUT] [/api/devices/{orgId}]

+ Request (application/json)

       Device json with 4 fields :

       {
           "name" : "My New Device",
           "boardType" : "ESP8266",
           "connectionType" : "WI_FI",
           "productId" : 1
       }

+ Response 200 (application/json)

        Full device json

## Update Device [POST] [/api/devices/{orgId}]

+ Request (application/json)

        Full product json (with id field)

+ Response 200 (application/json)

        Full device json

## Update Device MetaField [POST] [/api/devices/{orgId}/{deviceId}/updateMetaField]

+ Request (application/json)

   Json of modified metaField.

+ Response 200 (application/json)

+ Response 400 (application/json)

    MetaField with passed id not found.

+ Response 400 (application/json)

    Device not found.

+ Response 403 (application/json)

    You have no access to this device.

## Delete Device [DELETE] [/api/devices/{orgId}/{deviceId}]

+ Request (application/json)

+ Response 200 (application/json)

## Get device timeline [GET] [/api/devices/{orgId}/{deviceId}/timeline?eventType=CRITICAL&from=1&to=1496949455462&limit=10&offset=0&isResolved=true]

+ Request (application/json)

+ Response 200 (application/json)


        {
          "totalCritical" : 0,
          "totalWarning" : 0,
          "totalResolved" : 1,
          "logEvents" :
          [
              {
                "id" : 554,
                "deviceId" : 1,
                "eventType" : "CRITICAL",
                "ts" : 1497290276606,
                "eventHashcode" : 613812780,
                "description" : "This is my description",
                "isResolved" : true,
                "resolvedBy" : "Vasya Pupkin",
                "resolvedAt" : 1497290276606,
                "resolveComment" : "My resolve comment",
                "name" : "Temp is super high"
              }
          ]
        }

+ Response 500 (application/json)

## Resolve Log Event [POST] [/api/devices/{orgId}/{deviceId}/resolveEvent/{logEventId}]

+ Request (application/json)

        {
            "comment" : "My resolve comment"
        }

+ Response 200 (application/json)

+ Response 500 (application/json)

        Error marking event as resolved.


## Get graph history for 1 data stream [POST] [/api/data/{deviceId}/history]

+ Request (application/json)

        {
          "dataQueryRequests" : [
              {
                "sourceType" : "RAW_DATA", //RAW_DATA, SUM, AVG, MED, MIN, MAX, COUNT, CUMULATIVE_COUNT
                "pinType" : "VIRTUAL",
                "pin" : 1,
                "selectedColumns" : [
                    {
                      "name" : "Shift 1",
                      "type" : "METADATA" // or COLUMN
                    }
                ],
                "groupByFields" : [
                    {
                      "name" : "Shift 1",
                      "type" : "METADATA"
                    }
                ],
                "sortByFields" : [
                    {
                      "name" : "Shift 1",
                      "type" : "METADATA"
                    }
                ],
                "offset" : 0,
                "limit" : 1000,
                "from" : 0,
                "to" : 1507792950421,
                "deviceId" : 0
              }
           ]
        }

+ Response 200 (application/json)

        [
            {
               "data":[{"1507809234902":123.0}]
            },
            {
               "data":[{"1507809234902":124.0}]
            }
        ]

+ Response 400 (application/json)

    Device not found.

+ Response 403 (application/json)

    You have no access to this device.

## Insert 1 point into graph [GET] [/api/data/{deviceId}/insert?dataStream=V1&from=0&to=12321312&value=123]

+ Request (application/json)

+ Response 200 (application/json)

+ Response 400 (application/json)

    Device not found.

+ Response 403 (application/json)

    You have no access to this device.

## Insert 1 point into graph with ts [GET] [/api/data/{deviceId}/insert?dataStream=V1&from=0&to=12321312&value=123&ts=123]

+ Request (application/json)

+ Response 200 (application/json)

+ Response 400 (application/json)

    Device not found.

+ Response 403 (application/json)

    You have no access to this device.

#External API

## Create Log Event [GET] [/external/api/{token}/logEvent?code={code}]

+ Request (application/json)

+ Response 200 (application/json)

+ Response 500 (application/json)

## Update pin value via get request [GET] [/external/api/{token}/update/{pin}?value={value}]

+ Request (application/json)

+ Response 200 (application/json)