FORMAT: 1A
HOST: https://knight-qa.blynk.cc/


# Login API

## Login [POST] [/login]

+ Request (application/x-www-form-urlencoded)

       "email" : "admin@blynk.cc"
       "password" : "84inR6aLx6tZGaQyLrZSEVYCxWW8L88MG+gOn2cncgM=" //SHA256 hash of password salted with username.toLowerCase
        
+ Response 200 (application/json)

        User json with cookie "session".

+ Response 401 (application/json)

        Email or password is empty, user not exists or password is wrong.
        
+ Response 500 (application/json)

        Unexpected server error, probably wrong content-type.

## Logout [POST] [/logout]

+ Request (application/json)
        
+ Response 301 (application/json)

        /dashboard


# Organizations API

## Get organization assigned to user [GET] [/organization]

+ Request (application/json)

+ Response 200 (application/json)

        Json of user organization

+ Response 401 (application/json)

        User is not authorized to make this request.

+ Response 500 (application/json)

        Unexpected error.

## Create New Organization [PUT] [/organization]

+ Request (application/json)

        Full organization json (without id field)

+ Response 200 (application/json)

        Full organization json

+ Response 401 (application/json)

        User is not authorized to make this request.

+ Response 500 (application/json)

        Unexpected error.

## Update Organization [POST] [/organization]

+ Request (application/json)

        Full organization json (with id field)

+ Response 200 (application/json)

        Full organization json

+ Response 401 (application/json)

        User is not authorized to make this request.

+ Response 500 (application/json)

        Unexpected error.

## Delete Organization [DELETE] [/organization/{id}]

+ Request (application/json)

+ Response 200 (application/json)

+ Response 401 (application/json)

        User is not authorized to make this request or user tries to remove initial organization.

+ Response 500 (application/json)

        Unexpected error.


# Account API

## Get Account Info [GET] [/account]

+ Request (application/json)

+ Response 200 (application/json)

        User json

+ Response 401 (application/json)

        User is not authorized to make this request.

## Update Account Info [POST] [/account]

+ Request (application/json)

        Full user json

+ Response 200 (application/json)

        Full user json

+ Response 401 (application/json)

        User is not authorized to make this request.


## Send reset password email [POST] [/account/resetPass]

+ Request (application/json)

+ Response 200 (application/json)

        Email was sent.

+ Response 400 (application/json)

        Error sending reset email.


# Products API

## Get List Of Products [GET] [/product]

+ Request (application/json)

+ Response 200 (application/json)

        List of products for current user organization

+ Response 401 (application/json)

        User is not authorized to make this request.

## Create New Product [PUT] [/product]

+ Request (application/json)

        Full product json (without id field)

+ Response 200 (application/json)

        Full product json

+ Response 401 (application/json)

        User is not authorized to make this request.

## Update Product [POST] [/product]

+ Request (application/json)

        Full product json (with id field)

+ Response 200 (application/json)

        Full product json

+ Response 401 (application/json)

        User is not authorized to make this request.

## Delete Product [DELETE] [/product/{id}]

+ Request (application/json)

+ Response 200 (application/json)

+ Response 400 (application/json)

        User not allowed to delete product (not admin) or product with passed id not found.

+ Response 500 (application/json)

        Unexpected error.


## Upload API [POST] [/upload]

+ Request (multipart/form-data)

        File content.

+ Response 200 (application/json)

        Full path to uploaded image. For example : '/static/FUp_5716167699683281586_logo.png'.
        Product and Org has logoUrl field you need to set with that url

+ Response 401 (application/json)

        User is not authorized to make this request.