export const HARDWARE_DEFAULT = 'Particle Electron';
export const HARDWARES = [
  'Arduino 101',
  'Arduino Due',
  'Arduino Leonardo',
  'Arduino Mega',
  'Arduino Micro',
  'Arduino Mini',
  'Arduino MKR1000',
  'Arduino Nano',
  'Arduino Pro Micro',
  'Arduino Pro Mini',
  'Arduino UNO',
  'Arduino Yun',
  'Arduino Zero',
  'ESP8266',
  'Generic Board',
  'Intel Edison',
  'Intel Galileo',
  'LinkIt ONE',
  'Microduino Core+',
  'Microduino Core',
  'Microduino CoreRF',
  'Microduino CoreUSB',
  'NodeMCU',
  'Particle Core',
  'Particle Electron',
  'Particle Photon',
  'Raspberry Pi 3 B',
  'Raspberry Pi 2/A+/B+',
  'Raspberry Pi B (Rev1)',
  'Raspberry Pi A/B (Rev2)',
  'RedBearLab CC3200/Mini',
  'Seeed Wio Link',
  'SparkFun Blynk Board',
  'SparkFun ESP8266 Thing',
  'SparkFun Photon RedBoard',
  'TI CC3200-LaunchXL',
  'TI Tiva C Connected',
  'TinyDuino',
  'WeMos D1',
  'WeMos D1 mini',
  'Wildfire v2',
  'Wildfire v3',
  'Wildfire v4',
  'WiPy',
];

export const CONNECTIONS_TYPES_DEFAULT = 'GSM';
export const CONNECTIONS_TYPES = [
  'ETHERNET',
  'WI_FI',
  'USB',
  'BLUETOOTH',
  'BLE',
  'GSM'
];
