package cc.blynk.server.web.handlers;

import cc.blynk.server.Holder;
import cc.blynk.server.common.handlers.CommonGetDevicesByReferenceMetafieldLogic;
import cc.blynk.server.common.handlers.logic.timeline.WebGetDeviceTimelineLogic;
import cc.blynk.server.common.handlers.logic.timeline.WebResolveLogEventLogic;
import cc.blynk.server.web.handlers.logic.device.WebCreateOrgDeviceLogic;
import cc.blynk.server.web.handlers.logic.device.WebDeleteOrgDeviceLogic;
import cc.blynk.server.web.handlers.logic.device.WebEditDeviceMetafieldLogic;
import cc.blynk.server.web.handlers.logic.device.WebEditOrgDeviceLogic;
import cc.blynk.server.web.handlers.logic.device.WebGetGraphDataLogic;
import cc.blynk.server.web.handlers.logic.device.WebGetMetaFieldLogic;
import cc.blynk.server.web.handlers.logic.device.WebGetOrgDeviceLogic;
import cc.blynk.server.web.handlers.logic.device.WebGetOrgDevicesLogic;
import cc.blynk.server.web.handlers.logic.device.WebSetAuthTokenForDeviceLogic;
import cc.blynk.server.web.handlers.logic.device.WebTrackDeviceLogic;
import cc.blynk.server.web.handlers.logic.device.control.WebAppControlHardwareLogic;
import cc.blynk.server.web.handlers.logic.organization.WebCreateOrganizationLogic;
import cc.blynk.server.web.handlers.logic.organization.WebDeleteOrganizationLogic;
import cc.blynk.server.web.handlers.logic.organization.WebEditOrganizationLogic;
import cc.blynk.server.web.handlers.logic.organization.WebEditOwnOrganizationLogic;
import cc.blynk.server.web.handlers.logic.organization.WebEditRuleGroupLogic;
import cc.blynk.server.web.handlers.logic.organization.WebGetDeviceCountFromProductIDLogic;
import cc.blynk.server.web.handlers.logic.organization.WebGetDeviceCountLogic;
import cc.blynk.server.web.handlers.logic.organization.WebGetOrganizationLogic;
import cc.blynk.server.web.handlers.logic.organization.WebGetOrganizationsHierarchyLogic;
import cc.blynk.server.web.handlers.logic.organization.WebGetOrganizationsLogic;
import cc.blynk.server.web.handlers.logic.organization.WebGetProductLocationsLogic;
import cc.blynk.server.web.handlers.logic.organization.WebGetRuleGroupLogic;
import cc.blynk.server.web.handlers.logic.organization.WebGetTempSecureTokenLogic;
import cc.blynk.server.web.handlers.logic.organization.WebTrackOrganizationLogic;
import cc.blynk.server.web.handlers.logic.organization.ota.WebDeleteShipmentLogic;
import cc.blynk.server.web.handlers.logic.organization.ota.WebGetFirmwareInfoLogic;
import cc.blynk.server.web.handlers.logic.organization.ota.WebGetOrgShipmentsLogic;
import cc.blynk.server.web.handlers.logic.organization.ota.WebStartOtaLogic;
import cc.blynk.server.web.handlers.logic.organization.ota.WebStopOtaLogic;
import cc.blynk.server.web.handlers.logic.organization.roles.WebCreateRoleLogic;
import cc.blynk.server.web.handlers.logic.organization.roles.WebDeleteRoleLogic;
import cc.blynk.server.web.handlers.logic.organization.roles.WebEditRoleLogic;
import cc.blynk.server.web.handlers.logic.organization.roles.WebGetRoleLogic;
import cc.blynk.server.web.handlers.logic.organization.roles.WebGetRolesLogic;
import cc.blynk.server.web.handlers.logic.organization.roles.WebGetUserCountersByRoleLogic;
import cc.blynk.server.web.handlers.logic.organization.users.WebCanInviteUserLogic;
import cc.blynk.server.web.handlers.logic.organization.users.WebDeleteUserLogic;
import cc.blynk.server.web.handlers.logic.organization.users.WebEditUserInfoLogic;
import cc.blynk.server.web.handlers.logic.organization.users.WebGetOrgUsersLogic;
import cc.blynk.server.web.handlers.logic.organization.users.WebInviteUserLogic;
import cc.blynk.server.web.handlers.logic.product.WebCanDeleteProductLogic;
import cc.blynk.server.web.handlers.logic.product.WebCreateProductLogic;
import cc.blynk.server.web.handlers.logic.product.WebDeleteProductLogic;
import cc.blynk.server.web.handlers.logic.product.WebEditDevicesMetaInProductLogic;
import cc.blynk.server.web.handlers.logic.product.WebEditProductLogic;
import cc.blynk.server.web.handlers.logic.product.WebGetProductLogic;
import cc.blynk.server.web.handlers.logic.product.WebGetProductsLogic;

/**
 * The Blynk Project.
 * Created by Dmitriy Dumanskiy.
 * Created on 06.02.19.
 */
public final class WebAppLogicHolder {

    final WebAppControlHardwareLogic webAppControlHardwareLogic;
    final WebGetGraphDataLogic webGetGraphDataLogic;
    final WebResolveLogEventLogic webResolveLogEventLogic;
    final WebCreateOrgDeviceLogic webCreateOrgDeviceLogic;
    final WebGetOrgDeviceLogic webGetOrgDeviceLogic;
    final WebGetOrganizationLogic webGetOrganizationLogic;
    final WebGetOrganizationsLogic webGetOrganizationsLogic;
    final WebGetOrgUsersLogic webGetOrgUsersLogic;
    final WebGetProductLocationsLogic webGetProductLocationsLogic;
    final WebCanInviteUserLogic webCanInviteUserLogic;
    final WebCreateProductLogic webCreateProductLogic;
    final WebGetProductsLogic webGetProductsLogic;
    final WebDeleteProductLogic webDeleteProductLogic;
    final WebEditOrgDeviceLogic webEditOrgDeviceLogic;
    final WebEditDevicesMetaInProductLogic webEditDevicesMetaInProductLogic;
    final WebEditUserInfoLogic webEditUserInfoLogic;
    final WebDeleteUserLogic webDeleteUserLogic;
    final WebCreateOrganizationLogic webCreateOrganizationLogic;
    final WebEditOrganizationLogic webEditOrganizationLogic;
    final WebDeleteOrganizationLogic webDeleteOrganizationLogic;
    final WebCanDeleteProductLogic webCanDeleteProductLogic;
    final WebInviteUserLogic webInviteUserLogic;
    final WebGetDeviceTimelineLogic webGetDeviceTimelineLogic;
    final WebDeleteOrgDeviceLogic webDeleteOrgDeviceLogic;
    final WebGetOrganizationsHierarchyLogic webGetOrganizationsHierarchyLogic;
    final WebCreateRoleLogic webCreateRoleLogic;
    final WebEditRoleLogic webEditRoleLogic;
    final WebGetRolesLogic webGetRolesLogic;
    final WebDeleteRoleLogic webDeleteRoleLogic;
    final WebGetRoleLogic webGetRoleLogic;
    final WebGetOrgDevicesLogic webGetOrgDevicesLogic;
    final WebGetProductLogic webGetProductLogic;
    final WebEditProductLogic webEditProductLogic;
    final WebSetAuthTokenForDeviceLogic webSetAuthTokenForDeviceLogic;
    final WebEditOwnOrganizationLogic webEditOwnOrganizationLogic;
    final WebGetFirmwareInfoLogic webGetFirmwareInfoLogic;
    final WebStartOtaLogic webStartOtaLogic;
    final WebStopOtaLogic webStopOtaLogic;
    final WebDeleteShipmentLogic webCleanOtaLogic;
    final WebTrackOrganizationLogic webTrackOrganizationLogic;
    final WebEditDeviceMetafieldLogic webEditDeviceMetafieldLogic;
    final WebTrackDeviceLogic webTrackDeviceLogic;
    final WebGetDeviceCountLogic webGetDeviceCountLogic;
    final WebGetDeviceCountFromProductIDLogic webGetDeviceCountFromProductIDLogic;
    final WebGetUserCountersByRoleLogic webGetUserCountersByRoleLogic;
    final WebGetRuleGroupLogic webGetRuleGroupLogic;
    final WebEditRuleGroupLogic webEditRuleGroupLogic;
    final WebGetOrgShipmentsLogic webGetOrgShipmentsLogic;
    final WebGetMetaFieldLogic webGetMetaFieldLogic;
    final WebGetTempSecureTokenLogic webGetTempSecureTokenLogic;
    final CommonGetDevicesByReferenceMetafieldLogic commonGetDevicesByReferenceMetafieldLogic;

    public WebAppLogicHolder(Holder holder) {
        this.webAppControlHardwareLogic = new WebAppControlHardwareLogic(holder);
        this.webGetGraphDataLogic = new WebGetGraphDataLogic(holder);
        this.webResolveLogEventLogic = new WebResolveLogEventLogic(holder);
        this.webCreateOrgDeviceLogic = new WebCreateOrgDeviceLogic(holder);
        this.webGetOrgDeviceLogic = new WebGetOrgDeviceLogic(holder);
        this.webGetOrganizationLogic = new WebGetOrganizationLogic(holder);
        this.webGetOrganizationsLogic = new WebGetOrganizationsLogic(holder);
        this.webGetOrgUsersLogic = new WebGetOrgUsersLogic(holder);
        this.webGetProductLocationsLogic = new WebGetProductLocationsLogic(holder);
        this.webCanInviteUserLogic = new WebCanInviteUserLogic(holder);
        this.webCreateProductLogic = new WebCreateProductLogic(holder);
        this.webGetProductsLogic = new WebGetProductsLogic(holder);
        this.webDeleteProductLogic = new WebDeleteProductLogic(holder);
        this.webEditOrgDeviceLogic = new WebEditOrgDeviceLogic(holder);
        this.webEditDevicesMetaInProductLogic = new WebEditDevicesMetaInProductLogic(holder);
        this.webEditUserInfoLogic = new WebEditUserInfoLogic(holder);
        this.webDeleteUserLogic = new WebDeleteUserLogic(holder);
        this.webCreateOrganizationLogic = new WebCreateOrganizationLogic(holder);
        this.webEditOrganizationLogic = new WebEditOrganizationLogic(holder);
        this.webDeleteOrganizationLogic = new WebDeleteOrganizationLogic(holder);
        this.webCanDeleteProductLogic = new WebCanDeleteProductLogic(holder);
        this.webInviteUserLogic = new WebInviteUserLogic(holder);
        this.webGetDeviceTimelineLogic = new WebGetDeviceTimelineLogic(holder);
        this.webDeleteOrgDeviceLogic = new WebDeleteOrgDeviceLogic(holder);
        this.webGetOrganizationsHierarchyLogic = new WebGetOrganizationsHierarchyLogic(holder);
        this.webCreateRoleLogic = new WebCreateRoleLogic(holder);
        this.webEditRoleLogic = new WebEditRoleLogic(holder);
        this.webGetRolesLogic = new WebGetRolesLogic(holder);
        this.webDeleteRoleLogic = new WebDeleteRoleLogic(holder);
        this.webGetRoleLogic = new WebGetRoleLogic(holder);
        this.webGetOrgDevicesLogic = new WebGetOrgDevicesLogic(holder);
        this.webGetProductLogic = new WebGetProductLogic(holder);
        this.webEditProductLogic = new WebEditProductLogic(holder);
        this.webSetAuthTokenForDeviceLogic = new WebSetAuthTokenForDeviceLogic(holder);
        this.webEditOwnOrganizationLogic = new WebEditOwnOrganizationLogic(holder);
        this.webGetFirmwareInfoLogic = new WebGetFirmwareInfoLogic(holder);
        this.webStartOtaLogic = new WebStartOtaLogic(holder);
        this.webStopOtaLogic = new WebStopOtaLogic(holder);
        this.webCleanOtaLogic = new WebDeleteShipmentLogic(holder);
        this.webTrackOrganizationLogic = new WebTrackOrganizationLogic(holder);
        this.webEditDeviceMetafieldLogic = new WebEditDeviceMetafieldLogic(holder);
        this.webTrackDeviceLogic = new WebTrackDeviceLogic(holder);
        this.webGetDeviceCountLogic = new WebGetDeviceCountLogic(holder);
        this.webGetDeviceCountFromProductIDLogic = new WebGetDeviceCountFromProductIDLogic(holder);
        this.webGetUserCountersByRoleLogic = new WebGetUserCountersByRoleLogic(holder);
        this.webGetRuleGroupLogic = new WebGetRuleGroupLogic(holder);
        this.webEditRuleGroupLogic = new WebEditRuleGroupLogic(holder);
        this.webGetOrgShipmentsLogic = new WebGetOrgShipmentsLogic(holder);
        this.webGetMetaFieldLogic = new WebGetMetaFieldLogic(holder);
        this.webGetTempSecureTokenLogic = new WebGetTempSecureTokenLogic(holder);
        this.commonGetDevicesByReferenceMetafieldLogic = new CommonGetDevicesByReferenceMetafieldLogic(holder);
    }
}
