export default {
  "Pacific/Midway": "(UTC-11:00) Pacific/Midway",
  "Pacific/Niue": "(UTC-11:00) Pacific/Niue",
  "Pacific/Pago Pago": "(UTC-11:00) Pacific/Pago Pago",
  "Pacific/Honolulu": "(UTC-10:00) Pacific/Honolulu",
  "Pacific/Johnston": "(UTC-10:00) Pacific/Johnston",
  "Pacific/Rarotonga": "(UTC-10:00) Pacific/Rarotonga",
  "Pacific/Tahiti": "(UTC-10:00) Pacific/Tahiti",
  "America/Anchorage": "(UTC-09:00) America/Anchorage",
  "America/Juneau": "(UTC-09:00) America/Juneau",
  "America/Nome": "(UTC-09:00) America/Nome",
  "America/Sitka": "(UTC-09:00) America/Sitka",
  "America/Yakutat": "(UTC-09:00) America/Yakutat",
  "America/Santa Isabel": "(UTC-08:00) America/Santa Isabel",
  "America/Dawson": "(UTC-08:00) America/Dawson",
  "America/Los Angeles": "(UTC-08:00) America/Los Angeles",
  "America/Tijuana": "(UTC-08:00) America/Tijuana",
  "America/Vancouver": "(UTC-08:00) America/Vancouver",
  "America/Whitehorse": "(UTC-08:00) America/Whitehorse",
  "America/Creston": "(UTC-07:00) America/Creston",
  "America/Dawson Creek": "(UTC-07:00) America/Dawson Creek",
  "America/Hermosillo": "(UTC-07:00) America/Hermosillo",
  "America/Phoenix": "(UTC-07:00) America/Phoenix",
  "America/Chihuahua": "(UTC-07:00) America/Chihuahua",
  "America/Mazatlan": "(UTC-07:00) America/Mazatlan",
  "America/Boise": "(UTC-07:00) America/Boise",
  "America/Cambridge Bay": "(UTC-07:00) America/Cambridge Bay",
  "America/Denver": "(UTC-07:00) America/Denver",
  "America/Edmonton": "(UTC-07:00) America/Edmonton",
  "America/Inuvik": "(UTC-07:00) America/Inuvik",
  "America/Ojinaga": "(UTC-07:00) America/Ojinaga",
  "America/Yellowknife": "(UTC-07:00) America/Yellowknife",
  "America/Belize": "(UTC-06:00) America/Belize",
  "America/Costa Rica": "(UTC-06:00) America/Costa Rica",
  "America/El Salvador": "(UTC-06:00) America/El Salvador",
  "America/Guatemala": "(UTC-06:00) America/Guatemala",
  "America/Managua": "(UTC-06:00) America/Managua",
  "America/Tegucigalpa": "(UTC-06:00) America/Tegucigalpa",
  "Pacific/Galapagos": "(UTC-06:00) Pacific/Galapagos",
  "America/Chicago": "(UTC-06:00) America/Chicago",
  "America/Indiana/Knox": "(UTC-06:00) America/Indiana/Knox",
  "America/Indiana/Tell City": "(UTC-06:00) America/Indiana/Tell City",
  "America/Matamoros": "(UTC-06:00) America/Matamoros",
  "America/Menominee": "(UTC-06:00) America/Menominee",
  "America/North Dakota/Beulah": "(UTC-06:00) America/North Dakota/Beulah",
  "America/North Dakota/Center": "(UTC-06:00) America/North Dakota/Center",
  "America/North Dakota/New Salem": "(UTC-06:00) America/North Dakota/New Salem",
  "America/Rainy River": "(UTC-06:00) America/Rainy River",
  "America/Rankin Inlet": "(UTC-06:00) America/Rankin Inlet",
  "America/Resolute": "(UTC-06:00) America/Resolute",
  "America/Winnipeg": "(UTC-06:00) America/Winnipeg",
  "America/Bahia Banderas": "(UTC-06:00) America/Bahia Banderas",
  "America/Cancun": "(UTC-06:00) America/Cancun",
  "America/Merida": "(UTC-06:00) America/Merida",
  "America/Mexico City": "(UTC-06:00) America/Mexico City",
  "America/Monterrey": "(UTC-06:00) America/Monterrey",
  "America/Regina": "(UTC-06:00) America/Regina",
  "America/Swift Current": "(UTC-06:00) America/Swift Current",
  "America/Bogota": "(UTC-05:00) America/Bogota",
  "America/Cayman": "(UTC-05:00) America/Cayman",
  "America/Coral Harbour": "(UTC-05:00) America/Coral Harbour",
  "America/Eirunepe": "(UTC-05:00) America/Eirunepe",
  "America/Guayaquil": "(UTC-05:00) America/Guayaquil",
  "America/Jamaica": "(UTC-05:00) America/Jamaica",
  "America/Lima": "(UTC-05:00) America/Lima",
  "America/Panama": "(UTC-05:00) America/Panama",
  "America/Rio Branco": "(UTC-05:00) America/Rio Branco",
  "America/Detroit": "(UTC-05:00) America/Detroit",
  "America/Havana": "(UTC-05:00) America/Havana",
  "America/Indiana/Petersburg": "(UTC-05:00) America/Indiana/Petersburg",
  "America/Indiana/Vincennes": "(UTC-05:00) America/Indiana/Vincennes",
  "America/Indiana/Winamac": "(UTC-05:00) America/Indiana/Winamac",
  "America/Iqaluit": "(UTC-05:00) America/Iqaluit",
  "America/Kentucky/Monticello": "(UTC-05:00) America/Kentucky/Monticello",
  "America/Louisville": "(UTC-05:00) America/Louisville",
  "America/Montreal": "(UTC-05:00) America/Montreal",
  "America/Nassau": "(UTC-05:00) America/Nassau",
  "America/New York": "(UTC-05:00) America/New York",
  "America/Nipigon": "(UTC-05:00) America/Nipigon",
  "America/Pangnirtung": "(UTC-05:00) America/Pangnirtung",
  "America/Port-au-Prince": "(UTC-05:00) America/Port-au-Prince",
  "America/Thunder Bay": "(UTC-05:00) America/Thunder Bay",
  "America/Toronto": "(UTC-05:00) America/Toronto",
  "America/Indiana/Marengo": "(UTC-05:00) America/Indiana/Marengo",
  "America/Indiana/Vevay": "(UTC-05:00) America/Indiana/Vevay",
  "America/Indianapolis": "(UTC-05:00) America/Indianapolis",
  "America/Caracas": "(UTC-04:30) America/Caracas",
  "America/Asuncion": "(UTC-04:00) America/Asuncion",
  "America/Glace Bay": "(UTC-04:00) America/Glace Bay",
  "America/Goose Bay": "(UTC-04:00) America/Goose Bay",
  "America/Halifax": "(UTC-04:00) America/Halifax",
  "America/Moncton": "(UTC-04:00) America/Moncton",
  "America/Thule": "(UTC-04:00) America/Thule",
  "Atlantic/Bermuda": "(UTC-04:00) Atlantic/Bermuda",
  "America/Campo Grande": "(UTC-04:00) America/Campo Grande",
  "America/Cuiaba": "(UTC-04:00) America/Cuiaba",
  "America/Anguilla": "(UTC-04:00) America/Anguilla",
  "America/Antigua": "(UTC-04:00) America/Antigua",
  "America/Aruba": "(UTC-04:00) America/Aruba",
  "America/Barbados": "(UTC-04:00) America/Barbados",
  "America/Blanc-Sablon": "(UTC-04:00) America/Blanc-Sablon",
  "America/Boa Vista": "(UTC-04:00) America/Boa Vista",
  "America/Curacao": "(UTC-04:00) America/Curacao",
  "America/Dominica": "(UTC-04:00) America/Dominica",
  "America/Grand Turk": "(UTC-04:00) America/Grand Turk",
  "America/Grenada": "(UTC-04:00) America/Grenada",
  "America/Guadeloupe": "(UTC-04:00) America/Guadeloupe",
  "America/Guyana": "(UTC-04:00) America/Guyana",
  "America/Kralendijk": "(UTC-04:00) America/Kralendijk",
  "America/La Paz": "(UTC-04:00) America/La Paz",
  "America/Lower Princes": "(UTC-04:00) America/Lower Princes",
  "America/Manaus": "(UTC-04:00) America/Manaus",
  "America/Marigot": "(UTC-04:00) America/Marigot",
  "America/Martinique": "(UTC-04:00) America/Martinique",
  "America/Montserrat": "(UTC-04:00) America/Montserrat",
  "America/Port of Spain": "(UTC-04:00) America/Port of Spain",
  "America/Porto Velho": "(UTC-04:00) America/Porto Velho",
  "America/Puerto Rico": "(UTC-04:00) America/Puerto Rico",
  "America/Santo Domingo": "(UTC-04:00) America/Santo Domingo",
  "America/St Barthelemy": "(UTC-04:00) America/St Barthelemy",
  "America/St Kitts": "(UTC-04:00) America/St Kitts",
  "America/St Lucia": "(UTC-04:00) America/St Lucia",
  "America/St Thomas": "(UTC-04:00) America/St Thomas",
  "America/St Vincent": "(UTC-04:00) America/St Vincent",
  "America/Tortola": "(UTC-04:00) America/Tortola",
  "America/Santiago": "(UTC-04:00) America/Santiago",
  "Antarctica/Palmer": "(UTC-04:00) Antarctica/Palmer",
  "America/St Johns": "(UTC-03:30) America/St Johns",
  "America/Sao Paulo": "(UTC-03:00) America/Sao Paulo",
  "America/Argentina/La Rioja": "(UTC-03:00) America/Argentina/La Rioja",
  "America/Argentina/Rio Gallegos": "(UTC-03:00) America/Argentina/Rio Gallegos",
  "America/Argentina/Salta": "(UTC-03:00) America/Argentina/Salta",
  "America/Argentina/San Juan": "(UTC-03:00) America/Argentina/San Juan",
  "America/Argentina/San Luis": "(UTC-03:00) America/Argentina/San Luis",
  "America/Argentina/Tucuman": "(UTC-03:00) America/Argentina/Tucuman",
  "America/Argentina/Ushuaia": "(UTC-03:00) America/Argentina/Ushuaia",
  "America/Buenos Aires": "(UTC-03:00) America/Buenos Aires",
  "America/Catamarca": "(UTC-03:00) America/Catamarca",
  "America/Cordoba": "(UTC-03:00) America/Cordoba",
  "America/Jujuy": "(UTC-03:00) America/Jujuy",
  "America/Mendoza": "(UTC-03:00) America/Mendoza",
  "America/Araguaina": "(UTC-03:00) America/Araguaina",
  "America/Belem": "(UTC-03:00) America/Belem",
  "America/Cayenne": "(UTC-03:00) America/Cayenne",
  "America/Fortaleza": "(UTC-03:00) America/Fortaleza",
  "America/Maceio": "(UTC-03:00) America/Maceio",
  "America/Paramaribo": "(UTC-03:00) America/Paramaribo",
  "America/Recife": "(UTC-03:00) America/Recife",
  "America/Santarem": "(UTC-03:00) America/Santarem",
  "Antarctica/Rothera": "(UTC-03:00) Antarctica/Rothera",
  "Atlantic/Stanley": "(UTC-03:00) Atlantic/Stanley",
  "America/Godthab": "(UTC-03:00) America/Godthab",
  "America/Montevideo": "(UTC-03:00) America/Montevideo",
  "America/Bahia": "(UTC-03:00) America/Bahia",
  "America/Noronha": "(UTC-02:00) America/Noronha",
  "Atlantic/South Georgia": "(UTC-02:00) Atlantic/South Georgia",
  "America/Scoresbysund": "(UTC-01:00) America/Scoresbysund",
  "Atlantic/Azores": "(UTC-01:00) Atlantic/Azores",
  "Atlantic/Cape Verde": "(UTC-01:00) Atlantic/Cape Verde",
  "Etc/UTC": "(UTC+00:00) Etc/UTC",
  "Europe/London": "(UTC+00:00) Europe/London",
  "Arctic/Longyearbyen": "(UTC+01:00) Arctic/Longyearbyen",
  "Europe/Amsterdam": "(UTC+01:00) Europe/Amsterdam",
  "Europe/Andorra": "(UTC+01:00) Europe/Andorra",
  "Europe/Berlin": "(UTC+01:00) Europe/Berlin",
  "Europe/Busingen": "(UTC+01:00) Europe/Busingen",
  "Europe/Gibraltar": "(UTC+01:00) Europe/Gibraltar",
  "Europe/Luxembourg": "(UTC+01:00) Europe/Luxembourg",
  "Europe/Malta": "(UTC+01:00) Europe/Malta",
  "Europe/Monaco": "(UTC+01:00) Europe/Monaco",
  "Europe/Oslo": "(UTC+01:00) Europe/Oslo",
  "Europe/Rome": "(UTC+01:00) Europe/Rome",
  "Europe/San Marino": "(UTC+01:00) Europe/San Marino",
  "Europe/Stockholm": "(UTC+01:00) Europe/Stockholm",
  "Europe/Vaduz": "(UTC+01:00) Europe/Vaduz",
  "Europe/Vatican": "(UTC+01:00) Europe/Vatican",
  "Europe/Vienna": "(UTC+01:00) Europe/Vienna",
  "Europe/Zurich": "(UTC+01:00) Europe/Zurich",
  "Europe/Belgrade": "(UTC+01:00) Europe/Belgrade",
  "Europe/Bratislava": "(UTC+01:00) Europe/Bratislava",
  "Europe/Budapest": "(UTC+01:00) Europe/Budapest",
  "Europe/Ljubljana": "(UTC+01:00) Europe/Ljubljana",
  "Europe/Podgorica": "(UTC+01:00) Europe/Podgorica",
  "Europe/Prague": "(UTC+01:00) Europe/Prague",
  "Europe/Tirane": "(UTC+01:00) Europe/Tirane",
  "Africa/Ceuta": "(UTC+01:00) Africa/Ceuta",
  "Europe/Brussels": "(UTC+01:00) Europe/Brussels",
  "Europe/Copenhagen": "(UTC+01:00) Europe/Copenhagen",
  "Europe/Madrid": "(UTC+01:00) Europe/Madrid",
  "Europe/Paris": "(UTC+01:00) Europe/Paris",
  "Europe/Sarajevo": "(UTC+01:00) Europe/Sarajevo",
  "Europe/Skopje": "(UTC+01:00) Europe/Skopje",
  "Europe/Warsaw": "(UTC+01:00) Europe/Warsaw",
  "Europe/Zagreb": "(UTC+01:00) Europe/Zagreb",
  "Africa/Algiers": "(UTC+01:00) Africa/Algiers",
  "Africa/Bangui": "(UTC+01:00) Africa/Bangui",
  "Africa/Brazzaville": "(UTC+01:00) Africa/Brazzaville",
  "Africa/Douala": "(UTC+01:00) Africa/Douala",
  "Africa/Kinshasa": "(UTC+01:00) Africa/Kinshasa",
  "Africa/Lagos": "(UTC+01:00) Africa/Lagos",
  "Africa/Libreville": "(UTC+01:00) Africa/Libreville",
  "Africa/Luanda": "(UTC+01:00) Africa/Luanda",
  "Africa/Malabo": "(UTC+01:00) Africa/Malabo",
  "Africa/Ndjamena": "(UTC+01:00) Africa/Ndjamena",
  "Africa/Niamey": "(UTC+01:00) Africa/Niamey",
  "Africa/Porto-Novo": "(UTC+01:00) Africa/Porto-Novo",
  "Africa/Tunis": "(UTC+01:00) Africa/Tunis",
  "Africa/Windhoek": "(UTC+01:00) Africa/Windhoek",
  "Asia/Nicosia": "(UTC+02:00) Asia/Nicosia",
  "Europe/Athens": "(UTC+02:00) Europe/Athens",
  "Europe/Bucharest": "(UTC+02:00) Europe/Bucharest",
  "Europe/Chisinau": "(UTC+02:00) Europe/Chisinau",
  "Asia/Beirut": "(UTC+02:00) Asia/Beirut",
  "Africa/Cairo": "(UTC+02:00) Africa/Cairo",
  "Asia/Damascus": "(UTC+02:00) Asia/Damascus",
  "Africa/Blantyre": "(UTC+02:00) Africa/Blantyre",
  "Africa/Bujumbura": "(UTC+02:00) Africa/Bujumbura",
  "Africa/Gaborone": "(UTC+02:00) Africa/Gaborone",
  "Africa/Harare": "(UTC+02:00) Africa/Harare",
  "Africa/Johannesburg": "(UTC+02:00) Africa/Johannesburg",
  "Africa/Kigali": "(UTC+02:00) Africa/Kigali",
  "Africa/Lubumbashi": "(UTC+02:00) Africa/Lubumbashi",
  "Africa/Lusaka": "(UTC+02:00) Africa/Lusaka",
  "Africa/Maputo": "(UTC+02:00) Africa/Maputo",
  "Africa/Maseru": "(UTC+02:00) Africa/Maseru",
  "Africa/Mbabane": "(UTC+02:00) Africa/Mbabane",
  "Europe/Helsinki": "(UTC+02:00) Europe/Helsinki",
  "Europe/Kiev": "(UTC+02:00) Europe/Kiev",
  "Europe/Mariehamn": "(UTC+02:00) Europe/Mariehamn",
  "Europe/Riga": "(UTC+02:00) Europe/Riga",
  "Europe/Sofia": "(UTC+02:00) Europe/Sofia",
  "Europe/Tallinn": "(UTC+02:00) Europe/Tallinn",
  "Europe/Uzhgorod": "(UTC+02:00) Europe/Uzhgorod",
  "Europe/Vilnius": "(UTC+02:00) Europe/Vilnius",
  "Europe/Zaporozhye": "(UTC+02:00) Europe/Zaporozhye",
  "Europe/Istanbul": "(UTC+03:00) Europe/Istanbul",
  "Asia/Jerusalem": "(UTC+02:00) Asia/Jerusalem",
  "Africa/Tripoli": "(UTC+02:00) Africa/Tripoli",
  "Asia/Amman": "(UTC+03:00) Asia/Amman",
  "Asia/Baghdad": "(UTC+03:00) Asia/Baghdad",
  "Europe/Kaliningrad": "(UTC+03:00) Europe/Kaliningrad",
  "Europe/Minsk": "(UTC+03:00) Europe/Minsk",
  "Asia/Aden": "(UTC+03:00) Asia/Aden",
  "Asia/Bahrain": "(UTC+03:00) Asia/Bahrain",
  "Asia/Kuwait": "(UTC+03:00) Asia/Kuwait",
  "Asia/Qatar": "(UTC+03:00) Asia/Qatar",
  "Asia/Riyadh": "(UTC+03:00) Asia/Riyadh",
  "Africa/Addis Ababa": "(UTC+03:00) Africa/Addis Ababa",
  "Africa/Asmera": "(UTC+03:00) Africa/Asmera",
  "Africa/Dar es Salaam": "(UTC+03:00) Africa/Dar es Salaam",
  "Africa/Djibouti": "(UTC+03:00) Africa/Djibouti",
  "Africa/Juba": "(UTC+03:00) Africa/Juba",
  "Africa/Kampala": "(UTC+03:00) Africa/Kampala",
  "Africa/Khartoum": "(UTC+03:00) Africa/Khartoum",
  "Africa/Mogadishu": "(UTC+03:00) Africa/Mogadishu",
  "Africa/Nairobi": "(UTC+03:00) Africa/Nairobi",
  "Antarctica/Syowa": "(UTC+03:00) Antarctica/Syowa",
  "Indian/Antananarivo": "(UTC+03:00) Indian/Antananarivo",
  "Indian/Comoro": "(UTC+03:00) Indian/Comoro",
  "Indian/Mayotte": "(UTC+03:00) Indian/Mayotte",
  "Asia/Tehran": "(UTC+03:30) Asia/Tehran",
  "Asia/Dubai": "(UTC+04:00) Asia/Dubai",
  "Asia/Muscat": "(UTC+04:00) Asia/Muscat",
  "Asia/Baku": "(UTC+04:00) Asia/Baku",
  "Europe/Moscow": "(UTC+04:00) Europe/Moscow",
  "Europe/Samara": "(UTC+04:00) Europe/Samara",
  "Europe/Simferopol": "(UTC+04:00) Europe/Simferopol",
  "Europe/Volgograd": "(UTC+04:00) Europe/Volgograd",
  "Indian/Mahe": "(UTC+04:00) Indian/Mahe",
  "Indian/Mauritius": "(UTC+04:00) Indian/Mauritius",
  "Indian/Reunion": "(UTC+04:00) Indian/Reunion",
  "Asia/Tbilisi": "(UTC+04:00) Asia/Tbilisi",
  "Asia/Yerevan": "(UTC+04:00) Asia/Yerevan",
  "Asia/Kabul": "(UTC+04:30) Asia/Kabul",
  "Antarctica/Mawson": "(UTC+05:00) Antarctica/Mawson",
  "Asia/Aqtau": "(UTC+05:00) Asia/Aqtau",
  "Asia/Aqtobe": "(UTC+05:00) Asia/Aqtobe",
  "Asia/Ashgabat": "(UTC+05:00) Asia/Ashgabat",
  "Asia/Dushanbe": "(UTC+05:00) Asia/Dushanbe",
  "Asia/Oral": "(UTC+05:00) Asia/Oral",
  "Asia/Samarkand": "(UTC+05:00) Asia/Samarkand",
  "Asia/Tashkent": "(UTC+05:00) Asia/Tashkent",
  "Indian/Kerguelen": "(UTC+05:00) Indian/Kerguelen",
  "Indian/Maldives": "(UTC+05:00) Indian/Maldives",
  "Asia/Karachi": "(UTC+05:00) Asia/Karachi",
  "Asia/Kolkata": "(UTC+05:30) Asia/Kolkata",
  "Asia/Colombo": "(UTC+05:30) Asia/Colombo",
  "Asia/Katmandu": "(UTC+05:45) Asia/Katmandu",
  "Antarctica/Vostok": "(UTC+06:00) Antarctica/Vostok",
  "Asia/Almaty": "(UTC+06:00) Asia/Almaty",
  "Asia/Bishkek": "(UTC+06:00) Asia/Bishkek",
  "Asia/Qyzylorda": "(UTC+06:00) Asia/Qyzylorda",
  "Asia/Urumqi": "(UTC+06:00) Asia/Urumqi",
  "Indian/Chagos": "(UTC+06:00) Indian/Chagos",
  "Asia/Dhaka": "(UTC+06:00) Asia/Dhaka",
  "Asia/Thimphu": "(UTC+06:00) Asia/Thimphu",
  "Asia/Yekaterinburg": "(UTC+06:00) Asia/Yekaterinburg",
  "Asia/Rangoon": "(UTC+06:30) Asia/Rangoon",
  "Indian/Cocos": "(UTC+06:30) Indian/Cocos",
  "Antarctica/Davis": "(UTC+07:00) Antarctica/Davis",
  "Asia/Bangkok": "(UTC+07:00) Asia/Bangkok",
  "Asia/Hovd": "(UTC+07:00) Asia/Hovd",
  "Asia/Jakarta": "(UTC+07:00) Asia/Jakarta",
  "Asia/Phnom Penh": "(UTC+07:00) Asia/Phnom Penh",
  "Asia/Pontianak": "(UTC+07:00) Asia/Pontianak",
  "Asia/Saigon": "(UTC+07:00) Asia/Saigon",
  "Asia/Vientiane": "(UTC+07:00) Asia/Vientiane",
  "Indian/Christmas": "(UTC+07:00) Indian/Christmas",
  "Asia/Novokuznetsk": "(UTC+07:00) Asia/Novokuznetsk",
  "Asia/Novosibirsk": "(UTC+07:00) Asia/Novosibirsk",
  "Asia/Omsk": "(UTC+07:00) Asia/Omsk",
  "Asia/Hong Kong": "(UTC+08:00) Asia/Hong Kong",
  "Asia/Macau": "(UTC+08:00) Asia/Macau",
  "Asia/Shanghai": "(UTC+08:00) Asia/Shanghai",
  "Asia/Krasnoyarsk": "(UTC+08:00) Asia/Krasnoyarsk",
  "Asia/Brunei": "(UTC+08:00) Asia/Brunei",
  "Asia/Kuala Lumpur": "(UTC+08:00) Asia/Kuala Lumpur",
  "Asia/Kuching": "(UTC+08:00) Asia/Kuching",
  "Asia/Makassar": "(UTC+08:00) Asia/Makassar",
  "Asia/Manila": "(UTC+08:00) Asia/Manila",
  "Asia/Singapore": "(UTC+08:00) Asia/Singapore",
  "Antarctica/Casey": "(UTC+08:00) Antarctica/Casey",
  "Australia/Perth": "(UTC+08:00) Australia/Perth",
  "Asia/Taipei": "(UTC+08:00) Asia/Taipei",
  "Asia/Choibalsan": "(UTC+08:00) Asia/Choibalsan",
  "Asia/Ulaanbaatar": "(UTC+08:00) Asia/Ulaanbaatar",
  "Asia/Irkutsk": "(UTC+09:00) Asia/Irkutsk",
  "Asia/Dili": "(UTC+09:00) Asia/Dili",
  "Asia/Jayapura": "(UTC+09:00) Asia/Jayapura",
  "Asia/Tokyo": "(UTC+09:00) Asia/Tokyo",
  "Pacific/Palau": "(UTC+09:00) Pacific/Palau",
  "Asia/Pyongyang": "(UTC+09:00) Asia/Pyongyang",
  "Asia/Seoul": "(UTC+09:00) Asia/Seoul",
  "Australia/Adelaide": "(UTC+09:30) Australia/Adelaide",
  "Australia/Broken Hill": "(UTC+09:30) Australia/Broken Hill",
  "Australia/Darwin": "(UTC+09:30) Australia/Darwin",
  "Australia/Brisbane": "(UTC+10:00) Australia/Brisbane",
  "Australia/Lindeman": "(UTC+10:00) Australia/Lindeman",
  "Australia/Melbourne": "(UTC+10:00) Australia/Melbourne",
  "Australia/Sydney": "(UTC+10:00) Australia/Sydney",
  "Antarctica/DumontDUrville": "(UTC+10:00) Antarctica/DumontDUrville",
  "Pacific/Guam": "(UTC+10:00) Pacific/Guam",
  "Pacific/Port Moresby": "(UTC+10:00) Pacific/Port Moresby",
  "Pacific/Saipan": "(UTC+10:00) Pacific/Saipan",
  "Pacific/Truk": "(UTC+10:00) Pacific/Truk",
  "Australia/Currie": "(UTC+10:00) Australia/Currie",
  "Australia/Hobart": "(UTC+10:00) Australia/Hobart",
  "Asia/Chita": "(UTC+10:00) Asia/Chita",
  "Asia/Khandyga": "(UTC+10:00) Asia/Khandyga",
  "Asia/Yakutsk": "(UTC+10:00) Asia/Yakutsk",
  "Antarctica/Macquarie": "(UTC+11:00) Antarctica/Macquarie",
  "Pacific/Efate": "(UTC+11:00) Pacific/Efate",
  "Pacific/Guadalcanal": "(UTC+11:00) Pacific/Guadalcanal",
  "Pacific/Kosrae": "(UTC+11:00) Pacific/Kosrae",
  "Pacific/Noumea": "(UTC+11:00) Pacific/Noumea",
  "Pacific/Ponape": "(UTC+11:00) Pacific/Ponape",
  "Asia/Sakhalin": "(UTC+11:00) Asia/Sakhalin",
  "Asia/Ust-Nera": "(UTC+11:00) Asia/Ust-Nera",
  "Asia/Vladivostok": "(UTC+11:00) Asia/Vladivostok",
  "Antarctica/McMurdo": "(UTC+12:00) Antarctica/McMurdo",
  "Pacific/Auckland": "(UTC+12:00) Pacific/Auckland",
  "Pacific/Funafuti": "(UTC+12:00) Pacific/Funafuti",
  "Pacific/Kwajalein": "(UTC+12:00) Pacific/Kwajalein",
  "Pacific/Majuro": "(UTC+12:00) Pacific/Majuro",
  "Pacific/Nauru": "(UTC+12:00) Pacific/Nauru",
  "Pacific/Tarawa": "(UTC+12:00) Pacific/Tarawa",
  "Pacific/Wake": "(UTC+12:00) Pacific/Wake",
  "Pacific/Wallis": "(UTC+12:00) Pacific/Wallis",
  "Pacific/Fiji": "(UTC+12:00) Pacific/Fiji",
  "Asia/Anadyr": "(UTC+12:00) Asia/Anadyr",
  "Asia/Kamchatka": "(UTC+12:00) Asia/Kamchatka",
  "Asia/Magadan": "(UTC+12:00) Asia/Magadan",
  "Asia/Srednekolymsk": "(UTC+12:00) Asia/Srednekolymsk",
  "Pacific/Enderbury": "(UTC+13:00) Pacific/Enderbury",
  "Pacific/Fakaofo": "(UTC+13:00) Pacific/Fakaofo",
  "Pacific/Tongatapu": "(UTC+13:00) Pacific/Tongatapu",
  "Pacific/Apia": "(UTC+13:00) Pacific/Apia"
};
